### PR TITLE
feat: avoid self-hosted fonts

### PR DESCRIPTION
**Pull request by rin-st**
Mentioned [here](https://github.com/scaffold-eth/scaffold-eth-2/pull/535#discussion_r1335872244)

Additional links:
[link rel="stylesheet"](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#unsupported-metadata)
[Preconnect](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#resource-hints)

google fonts code needed
```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree&display=swap" rel="stylesheet">
```

### CODE REVIEW

**Review by technophile-04 — APPROVED** [review]
Tysm @rin-st 🙌, Looks good to me

**Comment by carletex** [comment]
Thanks @rin-st!

Yes, I did mention that haha Also realized that might not be the optimal thing to do:

- Most people will remove the example UI folder
- We will be teaching the hacky way to import fonts (with the page router, it was way simpler to do)

In any case, no strong opinion on this. So whatever you and @technophile-04 think is best.

**Comment by rin-st** [comment]
@technophile-04 I'm voting for removing this pr then :)

**Comment by technophile-04** [comment]
> We will be teaching the hacky way to import fonts

 yup, even I had it in the back of mind! 

> @technophile-04 I'm voting for removing this pr then :)

yup let's close this, but Tysm Rinat 🙌

**Pull request closed without merging**
